### ISSUE TITLE
So has apla and/or genesis shut down - last post on an issue was over a year ago in 2018

### ISSUE THREAD

**Issue by tallship** [AplaProject/go-apla#746]
@c-darwin , Hello Oleg, 

I've been wondering what's been going on over the last year, the distribution of the 85% of all tokens, being unable over and over (and just tried again) to join the 'genesiscommunity' team on keybase, etc.

Have you shut down? I saw a bit of activity on your part recently but nothing substantive, no announcements, no news, information. The last thing I know was about a year ago when you had some 'community manager' handling questions in the genisiscommunity at keybase, and he sarted saying really weird things and people started piling up on him when he got really snotty with the members. 

I left at that point when it descended into a mess, and that guy was completely incapable of constructing a sentence that made sense. He just kept saying 'soon', to people when they asked questions and started insulting them.

I few months ago, I went to see if anything had changed and noticed that the team was gone, so I did a join attempt, but never heard anything back, so I've attempted again today.

1.) Does the community still exist? It's listed on your gist still.

2.) has the project stalled? Is it abandoned? Everyone that was involved that I asked said it was dead and abandoned.

3.) can you contact someone in that community to approve my join request? According to the gist that's where announcements are supposed to be made. I hope you got rid of that guy - he was mean, disrespectful and very insulting to everyone in the community and it kind of left you guys with a bad name with all of the fellow keybasers that have also told me that they don't even think that team/community still exists.

We all jumped through a lot of hoops, creating proofs, cutting and pasting and tagging our invitees, supporting your project etc., and I must say, I'm only one of hundreds that have been left extremely disappointed in the lack of transparency - not to mention that community organizer guy who just kept slinging insults at everyone.

Is any of this accurate? Is there somewhere else I should be monitoring? Or has the the apla/genesis project stalled?

Thank you, and looking forward to hearing back at your earliest convenience.

**Comment by desdeux** [comment]
As i understand, Genesis was reformed into [EzDapps Accelerator](https://telegra.ph/EzDapps-Accelerator-turns-dApps-to-big-businesses-and-mobile-marketplaces-07-05) and gen tokens will be swapped to easy tokens. You can try to ask on official apla telegram channel.

**Comment by Saurer** [comment]
Hello.
Thank you for your interest in AplaProject. While I can't speak on behalf of all our team members, especially Oleg, I just want to give you answers to some questions you asked.
Firstly, AplaProject is alive and well. You can see the contribution history to both go-apla and apla-front repos. I'm also not quite sure who told you that project is dead since I am a live example that it is still kicking ;) . You can get a clear look at team members in the AplaProject organization or check the contributions that I mentioned before.

As for request - I pulled some strings to bring whoever is responsible to provide you an answer about your issue.
While I can't (not won't) answer all of your questions, I hope this information brought some light to the current situation.

Best regards

**Comment by tallship** [comment]
@Saurer ,

Thank you so very much Frank :)

I had seen commits and other activity but was not sure what was going on due to the relative silence and an inability to see anything over at keybase other than a few grumbling folks.

I'm quite elated that the project  is active and moving forward, and looking forward to following that progress and being able to use the technology soon.

I've never really been a big fan of Bitcoin, due to the time lags and gas involved in mining fees, etc., and have really enjoyed using Stellar, but Genesis (or Apla? I've never been really clear on the differences) had piqued my interest as well from the first time it was introduced to me and I'm hoping to be able to use some of the smart contract features where github or other self-hosted git repos are concerned with projects I'm involved.

You have a wonderful day and I'll wait to see how the keybase thing unfolds :)

Kindest regards,

Bradley

.

**Comment by c-darwin** [comment]
Hi @tallship,
Unfortunately, I was not able to put together a large community around Genesis. I thought for a long time what to do. EzDapps promised to issue tokens to all users from Genesis and Apla. I think this is a good solution, because they will be traded on an exchange.
If someone wants to continue the ​​Genesis idea, then this is not difficult to do, the source code is publicly available and this is not abandoned.
Our team went through difficult times, we had to lay off more than half of the employees, but we continue to support the source code, which is now based in https://github.com/AplaProject
